def containername

pipeline {
    agent any
    stages {
        stage('Check Docker') {
            steps {
                powershell 'get-service docker'
            }
        }
        stage('check container') {
            steps {
					script {
                        containername = powershell(returnStdout: true, script:'docker ps -q -f status=running -f name=^/compiler$').trim()
						
						if ("${containername}"){
                            echo "${containername} is running!!"
                        }else{
							bat 'docker rm compiler'	
							bat 'docker run -it --name compiler -h compilerhost -p 8000:80 -v K:/Docker/dockervol:c:/dockervol microsoft/windowsservercore:1709'
                        }
                    }
            }
        }
        stage('Get In Container') {
 			steps{
                script {
                         bat 'docker exec -i compiler powershell -c c:/dockervol/abc.bat'
                }
            }    
        }
    }
}