def containername

pipeline {
    agent any
    stages {
        stage('Check Docker') {
            steps {
                powershell 'get-service docker'
            }
        }
        stage('remove container') {
            steps {
					bat 'docker stop compiler'
					bat 'docker rm compiler'		
            }
        }
		stage('start container') {
            steps {
					bat 'docker run -it --name compiler -h compilerhost --r always -p 8000:80 -v K:/Docker/dockervol:c:/dockervol microsoft/windowsservercore:1709'		
            }
        }
        stage('Get In Container') {
 			steps{
                script {
                         bat 'docker exec -i compiler powershell -c c:/dockervol/abc.bat'
                }
            }    
        }
    }
}