def containername

pipeline {
    agent any
    stages {
        stage('Check Docker') {
            steps {
                powershell 'get-service docker'
            }
        }
        stage('Container Operations') {
            steps {
				script {
					echo 'Checking if container is running...'
					containername = powershell(returnStdout: true, script:'docker ps -q -f status=running -f name=^/compiler$').trim()
					
					if ("${containername}"){
						echo "${containername} is running!!"
					}else{
						echo 'Checking if container is stopped...'
						stopped = powershell(returnStdout: true, script:'docker ps -q -f status=exited -f name=^/compiler$').trim()
						
						if (stopped){
							echo 'Stopped container named \"compiler\" found!!! ... starting it now'
							bat 'docker start compiler'	
						}else{
							echo 'Creating and running new container'
							bat 'docker create -i --name compiler -h compilerhost -p 8000:80 -v K:/Docker/dockervol:c:/dockervol microsoft/windowsservercore:1709'
							bat 'docker start compiler'
						}
					}
				}
            }
        }
        stage('Compiling Application') {
 			steps{
                script {
                         bat 'docker exec -i compiler powershell -c c:/dockervol/abc.bat'
                }
            }    
        }
		stage('Deploying Application') {
 			steps{
                script {
                         bat 'docker exec -i compiler powershell -c c:/dockervol/abc.bat'
                }
            }    
        }
		stage('Creating docker image') {
 			steps{
                script {
                         bat 'docker exec -i compiler powershell -c c:/dockervol/abc.bat'
                }
            }    
        }
		stage('Pushing image to registry') {
 			steps{
                script {
                         bat 'docker exec -i compiler powershell -c c:/dockervol/abc.bat'
                }
            }    
        }
    }
}